version: '3'
services:
  horse:
    image: ghcr.io/joint-online-judge/horse:test
    environment:
      DEBUG: "true"
  tiger-1:
    image: ghcr.io/joint-online-judge/tiger:test
    environment:
      DEBUG: "true"
